apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::553021162727:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-09T03:22:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1348"
  uid: e7d5bed4-ee3d-4dbb-a8dc-13e930330c90
