apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::553021162727:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-08T02:21:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1757"
  uid: 74997bbb-c1b4-499b-b71c-5c2518c809f8
