apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::553021162727:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-09T14:47:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1488"
  uid: 1021e733-2c52-41ea-ab33-d7daf283e878
