apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::553021162727:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-09T00:47:17Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1664"
  uid: 5b571f77-5cb8-4ca0-836a-0f7472dda8e5
